import type { PromptFinding, PromptDetectorCategory } from '@safeskill/shared';
import { PROMPT_INJECTION_PATTERNS } from '@safeskill/shared';

const CATEGORY: PromptDetectorCategory = 'hidden-text';

/**
 * Zero-width and invisible character ranges.
 * Includes soft hyphens, variation selectors, word joiners, and other invisible chars.
 */
const ZERO_WIDTH_RE = /[\u200B\u200C\u200D\uFEFF\u2060\u2061\u2062\u2063\u2064\u00AD\u034F\u180E\u200E\u200F\u2028\u2029\u205F\u2800]+/g;

/**
 * Bidirectional override characters.
 */
const BIDI_RE = /[\u202A\u202B\u202C\u202D\u202E\u2066\u2067\u2068\u2069]+/g;

/**
 * Unicode variation selectors (invisible, can hide intent).
 * Excludes U+FE0E (text presentation) and U+FE0F (emoji presentation)
 * which are standard selectors used by all emojis (e.g. ⚠️ ⚙️ 🏗️).
 */
const VARIATION_SELECTOR_RE = /[\uFE00-\uFE0D\u{E0100}-\u{E01EF}]+/gu;

/**
 * Homoglyph detection — non-ASCII characters mixed into otherwise-ASCII words.
 * Catches Cyrillic а/е/о/с/р mixed into English words like "рrосеss".
 * Requires at least one ASCII letter adjacent to the non-ASCII character,
 * so standalone Greek/math symbols (φ, γ, π) are NOT flagged.
 */
const HOMOGLYPH_WORD_RE = /(?:[a-z]+[\u0400-\u04FF\u0370-\u03FF\u0250-\u02AF\u1D00-\u1D7F\u1E00-\u1EFF\uFF00-\uFFEF][a-z]*|[a-z]*[\u0400-\u04FF\u0370-\u03FF\u0250-\u02AF\u1D00-\u1D7F\u1E00-\u1EFF\uFF00-\uFFEF][a-z]+)/gi;

/**
 * HTML comments in markdown.
 */
const HTML_COMMENT_RE = /<!--([\s\S]*?)-->/g;

/**
 * Null bytes.
 */
const NULL_BYTE_RE = /\x00+/g;

/**
 * Known benign HTML comment patterns — metadata used by registries and tooling.
 * These should never be flagged as hidden text.
 */
const BENIGN_COMMENT_PATTERNS = [
  /^\s*mcp-name:\s/i,
  /^\s*mcp-version:\s/i,
  /^\s*mcp-description:\s/i,
  /^\s*mcp-server-id:\s/i,
  /^\s*@license\b/i,
  /^\s*@copyright\b/i,
  /^\s*prettier-ignore/i,
  /^\s*eslint-disable/i,
  /^\s*stylelint-disable/i,
  /^\s*markdownlint-disable/i,
  /^\s*@generated\b/i,
  /^\s*@auto-generated\b/i,
  /^\s*generated by\b/i,
];

function isBenignMetadataComment(commentBody: string): boolean {
  const trimmed = commentBody.trim();
  return BENIGN_COMMENT_PATTERNS.some((re) => re.test(trimmed));
}

/**
 * Instruction-like patterns that, when found inside hidden text, massively
 * increase severity.
 */
const INSTRUCTION_INDICATORS = [
  /ignore/i,
  /override/i,
  /instruction/i,
  /system/i,
  /execute/i,
  /run\s/i,
  /fetch/i,
  /send/i,
  /read\s/i,
  /write\s/i,
  /curl/i,
  /bash/i,
  /shell/i,
  /forget/i,
  /disregard/i,
  /pretend/i,
  /you\s+are/i,
  /your\s+new/i,
  /include/i,
  /before\s+respond/i,
  /silently/i,
  /base64/i,
  /encode/i,
  /exfiltrat/i,
  /~\/.ssh/i,
  /~\/.aws/i,
  /credential/i,
  /api[_\s-]?key/i,
  /https?:\/\//i,
];

function containsInstructions(text: string): boolean {
  let hits = 0;
  for (const re of INSTRUCTION_INDICATORS) {
    if (re.test(text)) hits++;
    if (hits >= 2) return true;
  }
  return false;
}

function lineColFromIndex(content: string, index: number): { line: number; column: number } {
  const before = content.slice(0, index);
  const lines = before.split('\n');
  return { line: lines.length, column: (lines[lines.length - 1]?.length ?? 0) + 1 };
}

function snippet(content: string, index: number, length: number): string {
  const raw = content.slice(index, index + Math.min(length, 120));
  return raw.replace(/\n/g, '\\n');
}

/**
 * Decode zero-width characters to reveal the hidden payload.
 * Some steganography encodes binary using ZWJ/ZWNJ pairs.
 */
function decodeZeroWidth(text: string): string {
  // Show unicode code points for visibility
  return [...text].map((ch) => `U+${ch.codePointAt(0)!.toString(16).toUpperCase().padStart(4, '0')}`).join(' ');
}

interface HiddenMatch {
  regex: RegExp;
  technique: string;
  decodeHidden: (matchText: string, captured?: string) => string;
}

const MATCHERS: HiddenMatch[] = [
  {
    regex: ZERO_WIDTH_RE,
    technique: 'unicode-smuggling',
    decodeHidden: (matchText) => decodeZeroWidth(matchText),
  },
  {
    regex: BIDI_RE,
    technique: 'bidi-override',
    decodeHidden: (matchText) => decodeZeroWidth(matchText),
  },
  {
    regex: VARIATION_SELECTOR_RE,
    technique: 'variation-selector',
    decodeHidden: (matchText) => decodeZeroWidth(matchText),
  },
  {
    regex: HOMOGLYPH_WORD_RE,
    technique: 'homoglyph',
    decodeHidden: (matchText) => {
      const nonAscii = [...matchText].filter(c => c.codePointAt(0)! > 127);
      return `Word "${matchText}" contains non-ASCII lookalikes: ${nonAscii.map(c => `U+${c.codePointAt(0)!.toString(16).toUpperCase()}`).join(', ')}`;
    },
  },
  {
    regex: HTML_COMMENT_RE,
    technique: 'html-comment',
    decodeHidden: (_matchText, captured) => captured?.trim() ?? '',
  },
  {
    regex: NULL_BYTE_RE,
    technique: 'null-byte',
    decodeHidden: (matchText) => `${matchText.length} null byte(s)`,
  },
];

export function detect(
  content: string,
  filePath: string,
  isPriority: boolean,
): PromptFinding[] {
  const findings: PromptFinding[] = [];

  for (const { regex, technique, decodeHidden } of MATCHERS) {
    const globalRe = new RegExp(regex.source, regex.flags.includes('g') ? regex.flags : regex.flags + 'g');
    let match: RegExpExecArray | null;

    while ((match = globalRe.exec(content)) !== null) {
      const { line, column } = lineColFromIndex(content, match.index);
      const decoded = decodeHidden(match[0], match[1]);
      const hasInstructions = technique === 'html-comment'
        ? containsInstructions(match[1] ?? '')
        : containsInstructions(decoded);

      // Skip known benign metadata comments entirely (MCP registry, linter directives, etc.)
      if (technique === 'html-comment' && isBenignMetadataComment(match[1] ?? '')) {
        continue;
      }

      // Skip HTML comments at the very start of a file — these are frontmatter/metadata
      // (e.g. <!-- eval-variant\nname: v2-...\n --> or <!-- @generated by ... -->)
      if (technique === 'html-comment' && match.index === 0) {
        continue;
      }

      // HTML comments with benign content (e.g. <!-- TODO --> ) are low severity
      const isBenignComment =
        technique === 'html-comment' &&
        !hasInstructions &&
        (match[1]?.trim().length ?? 0) < 40;

      let severity: PromptFinding['severity'];
      let confidence: number;

      if (hasInstructions) {
        severity = 'critical';
        confidence = 0.95;
      } else if (isBenignComment) {
        severity = 'low';
        confidence = 0.2;
      } else {
        severity = isPriority ? 'high' : 'medium';
        confidence = isPriority ? 0.8 : 0.6;
      }

      const decodedPreview = decoded.length > 80 ? decoded.slice(0, 80) + '...' : decoded;
      const description = hasInstructions
        ? `Hidden text contains instruction-like payload (${technique}): "${decodedPreview}"`
        : `Hidden/invisible text detected (${technique}) at byte offset ${match.index}: "${decodedPreview}"`;

      findings.push({
        category: CATEGORY,
        severity,
        location: { file: filePath, line, column },
        description,
        contentSnippet: snippet(content, Math.max(0, match.index - 10), match[0].length + 20),
        confidence,
        technique,
      });
    }
  }

  return findings;
}
